# ─── Customer-managed KMS key for secret payloads ─────────────────────────────

resource "aws_kms_key" "secrets" {
  description             = "Encrypts application secrets for ${var.environment} vesting"
  deletion_window_in_days = 30
  enable_key_rotation     = true
}

resource "aws_kms_alias" "secrets" {
  name          = "alias/${var.environment}-vesting-secrets"
  target_key_id = aws_kms_key.secrets.key_id
}

# ─── Database credentials ────────────────────────────────────────────────────

# The bootstrap password is generated by Terraform rather than supplied through
# CI, so it never appears in an environment variable or a GitHub secret. After
# the first rotation cycle the rotation Lambda owns the value entirely.
resource "aws_secretsmanager_secret" "db_credentials" {
  name                    = "vesting/${var.environment}/db-credentials"
  description             = "PostgreSQL master credentials for ${var.environment} (auto-rotated every ${var.rotation_days} days)"
  kms_key_id              = aws_kms_key.secrets.arn
  recovery_window_in_days = 0

  tags = {
    Rotation     = "automatic"
    RotationDays = tostring(var.rotation_days)
  }
}

resource "aws_secretsmanager_secret_version" "db_credentials" {
  secret_id     = aws_secretsmanager_secret.db_credentials.id
  secret_string = jsonencode({
    username     = var.db_username
    password     = var.db_password
    host         = var.db_address
    port         = var.db_port
    dbname       = var.db_name
    database_url = "postgres://${var.db_username}:${urlencode(var.db_password)}@${var.db_address}:${var.db_port}/${var.db_name}"
  })
}

# ─── JWT RS256 signing key ───────────────────────────────────────────────────

# Rotation is manual so operators can stage a new key under the AWSPENDING
# label and promote it once sessions are re-issued. Versions are retained
# indefinitely, which is the grace period that already-issued tokens are
# verified against during a cutover.
resource "aws_secretsmanager_secret" "jwt_private_key" {
  name                    = "vesting/${var.environment}/jwt-rs256-private-key"
  description             = "RS256 private key for JWT signing in ${var.environment} (manual rotation with grace period)"
  kms_key_id              = aws_kms_key.secrets.arn
  recovery_window_in_days = 0

  tags = {
    Rotation = "manual"
  }
}

resource "tls_private_key" "jwt" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "aws_secretsmanager_secret_version" "jwt_private_key" {
  secret_id = aws_secretsmanager_secret.jwt_private_key.id
  # private_key_pem already carries the BEGIN/END markers.
  secret_string = tls_private_key.jwt.private_key_pem
}

# ─── Third-party credentials ─────────────────────────────────────────────────

# Values are optional at bootstrap. When omitted a random placeholder is stored
# so the wiring is testable and can be replaced later with
# `aws secretsmanager put-secret-value` without touching Terraform state.
resource "aws_secretsmanager_secret" "soroban_rpc_api_key" {
  name                    = "vesting/${var.environment}/soroban-rpc-api-key"
  description             = "Soroban RPC API key for ${var.environment}"
  kms_key_id              = aws_kms_key.secrets.arn
  recovery_window_in_days = 0

  tags = {
    Rotation = "manual"
  }
}

resource "random_password" "soroban_rpc_api_key" {
  length  = 40
  special = false
}

resource "aws_secretsmanager_secret_version" "soroban_rpc_api_key" {
  secret_id     = aws_secretsmanager_secret.soroban_rpc_api_key.id
  secret_string = coalesce(var.soroban_rpc_api_key, random_password.soroban_rpc_api_key.result)
}

resource "aws_secretsmanager_secret" "slack_webhook_url" {
  name                    = "vesting/${var.environment}/slack-webhook-url"
  description             = "Slack incoming webhook for ${var.environment} alert relay"
  kms_key_id              = aws_kms_key.secrets.arn
  recovery_window_in_days = 0

  tags = {
    Rotation = "manual"
  }
}

resource "aws_secretsmanager_secret_version" "slack_webhook_url" {
  secret_id     = aws_secretsmanager_secret.slack_webhook_url.id
  secret_string = var.slack_webhook_url
}

resource "aws_secretsmanager_secret" "sentry_dsn" {
  name                    = "vesting/${var.environment}/sentry-dsn"
  description             = "Sentry DSN for ${var.environment} error reporting"
  kms_key_id              = aws_kms_key.secrets.arn
  recovery_window_in_days = 0

  tags = {
    Rotation = "manual"
  }
}

resource "random_password" "sentry_dsn" {
  length  = 40
  special = false
}

resource "aws_secretsmanager_secret_version" "sentry_dsn" {
  secret_id     = aws_secretsmanager_secret.sentry_dsn.id
  secret_string = coalesce(var.sentry_dsn, random_password.sentry_dsn.result)
}

# ─── Rotation Lambda (PostgreSQL master password) ────────────────────────────

data "archive_file" "db_rotation" {
  type        = "zip"
  source_file = "${path.module}/rotation/index.js"
  output_path = "${path.module}/rotation/index.js.zip"
}

data "aws_iam_policy_document" "db_rotation_assume" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["lambda.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "db_rotation" {
  name               = "${var.environment}-vesting-db-rotation"
  assume_role_policy = data.aws_iam_policy_document.db_rotation_assume.json
}

data "aws_iam_policy_document" "db_rotation" {
  statement {
    sid    = "ReadAndRotateTargetSecret"
    effect = "Allow"
    actions = [
      "secretsmanager:GetSecretValue",
      "secretsmanager:PutSecretValue",
      "secretsmanager:UpdateSecret",
      "secretsmanager:DescribeSecret",
    ]
    resources = [aws_secretsmanager_secret.db_credentials.arn]
  }

  statement {
    sid    = "KmsDecryptAndEncrypt"
    effect = "Allow"
    actions = [
      "kms:Decrypt",
      "kms:Encrypt",
      "kms:GenerateDataKey",
    ]
    resources = [aws_kms_key.secrets.arn]
  }

  # Setting the new password is an in-place ModifyDBInstance call, so tasks keep
  # serving against the running instance for the whole rotation.
  statement {
    sid       = "ApplyMasterPassword"
    effect    = "Allow"
    actions   = ["rds:DescribeDBInstances", "rds:ModifyDBInstance"]
    resources = ["*"]
  }
}

resource "aws_iam_role_policy" "db_rotation" {
  name   = "${var.environment}-vesting-db-rotation"
  role   = aws_iam_role.db_rotation.id
  policy = data.aws_iam_policy_document.db_rotation.json
}

resource "aws_cloudwatch_log_group" "db_rotation" {
  name              = "/aws/lambda/${var.environment}-vesting-db-rotation"
  retention_in_days = 365
}

resource "aws_lambda_function" "db_rotation" {
  filename         = data.archive_file.db_rotation.output_path
  function_name    = "${var.environment}-vesting-db-rotation"
  role             = aws_iam_role.db_rotation.arn
  handler          = "index.handler"
  runtime          = "nodejs20.x"
  timeout          = 120
  source_code_hash = data.archive_file.db_rotation.output_base64sha256

  environment {
    variables = {
      DB_INSTANCE_IDENTIFIER = var.db_identifier
      SECRET_ARN            = aws_secretsmanager_secret.db_credentials.arn
    }
  }
}

resource "aws_secretsmanager_secret_rotation" "db_credentials" {
  secret_id            = aws_secretsmanager_secret.db_credentials.id
  rotation_lambda_arn = aws_lambda_function.db_rotation.arn

  rotation_rules {
    automatically_after_days = var.rotation_days
  }
}

# ─── Rotation failure alerting ───────────────────────────────────────────────

resource "aws_sns_topic" "rotation_failure" {
  name              = "${var.environment}-vesting-secret-rotation-failure"
  kms_master_key_id = "alias/aws/sns"
}

resource "aws_sns_topic_subscription" "rotation_failure_email" {
  for_each  = var.alert_emails
  topic_arn = aws_sns_topic.rotation_failure.arn
  protocol  = "email"
  endpoint  = each.value
}

# A failed rotation surfaces as a Lambda error, so the rotation function's
# Errors metric is what we alarm on.
resource "aws_cloudwatch_metric_alarm" "rotation_failure" {
  alarm_name          = "${var.environment}-vesting-secret-rotation-failed"
  alarm_description   = "Secret rotation Lambda failed for ${var.environment}. Inspect the AWSPENDING version of ${aws_secretsmanager_secret.db_credentials.name}."
  namespace           = "AWS/Lambda"
  metric_name         = "Errors"
  statistic           = "Sum"
  period              = 300
  evaluation_periods  = 1
  threshold           = 1
  comparison_operator = "GreaterThanOrEqualToThreshold"
  treat_missing_data  = "notBreaching"
  alarm_actions       = [aws_sns_topic.rotation_failure.arn]
  ok_actions          = [aws_sns_topic.rotation_failure.arn]

  dimensions = {
    FunctionName = aws_lambda_function.db_rotation.function_name
  }
}

# Secrets Manager also reports the failure directly as a RotateSecret API error.
# Routing that event to the same topic captures the failure even when the Lambda
# exits before CloudWatch closes the metric period.
resource "aws_cloudwatch_event_rule" "rotation_failed" {
  name        = "${var.environment}-vesting-secret-rotation-failed"
  description = "Secrets Manager rotation failures for ${var.environment}"

  event_pattern = jsonencode({
    source        = ["aws.secretsmanager"]
    "detail-type" = ["AWS API Call via CloudTrail"]
    detail = {
      eventSource = ["secretsmanager.amazonaws.com"]
      eventName   = ["RotateSecret"]
      errorCode   = ["*"]
    }
  })
}

resource "aws_cloudwatch_event_target" "rotation_failed" {
  rule       = aws_cloudwatch_event_rule.rotation_failed.name
  target_arn = aws_sns_topic.rotation_failure.arn
}

# EventBridge needs explicit publish rights on the topic, otherwise the rule
# matches but the notification is silently dropped.
data "aws_iam_policy_document" "rotation_failure_topic" {
  statement {
    sid       = "AllowEventBridgePublish"
    effect    = "Allow"
    actions   = ["SNS:Publish"]
    resources = [aws_sns_topic.rotation_failure.arn]

    principals {
      type        = "Service"
      identifiers = ["events.amazonaws.com"]
    }

    condition {
      test     = "ArnEquals"
      variable = "aws:SourceArn"
      values   = [aws_cloudwatch_event_rule.rotation_failed.arn]
    }
  }
}

resource "aws_sns_topic_policy" "rotation_failure" {
  arn    = aws_sns_topic.rotation_failure.arn
  policy = data.aws_iam_policy_document.rotation_failure_topic.json
}

# ─── CloudTrail audit of secret access ───────────────────────────────────────

resource "aws_cloudwatch_log_group" "secrets_audit" {
  name              = "/aws/cloudtrail/${var.environment}-vesting-secrets-audit"
  retention_in_days = 365
}

data "aws_caller_identity" "current" {}

data "aws_iam_policy_document" "cloudtrail_assume" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["cloudtrail.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "cloudtrail" {
  name               = "${var.environment}-vesting-secrets-audit"
  assume_role_policy = data.aws_iam_policy_document.cloudtrail_assume.json
}

data "aws_iam_policy_document" "cloudtrail" {
  statement {
    sid    = "WriteAuditLog"
    effect = "Allow"
    actions = [
      "logs:CreateLogStream",
      "logs:PutLogEvents",
    ]
    resources = ["${aws_cloudwatch_log_group.secrets_audit.arn}:*"]
  }

  statement {
    # CreateLogGroup is the only action that cannot be scoped to a log group.
    sid       = "CreateAuditLogGroup"
    effect    = "Allow"
    actions   = ["logs:CreateLogGroup"]
    resources = ["arn:aws:logs:${var.aws_region}:${data.aws_caller_identity.current.account_id}:*"]
  }

  statement {
    sid       = "DecryptAuditLog"
    effect    = "Allow"
    actions   = ["kms:Decrypt"]
    resources = [aws_kms_key.secrets.arn]
  }
}

resource "aws_iam_role_policy" "cloudtrail" {
  name   = "${var.environment}-vesting-secrets-audit"
  role   = aws_iam_role.cloudtrail.id
  policy = data.aws_iam_policy_document.cloudtrail.json
}

# Scoped to this environment's secrets so the trail stays a readable audit log
# rather than a firehose of unrelated account activity. Delivered to CloudWatch
# Logs with a one-year retention, which is where the audit queries in the
# runbook read from.
resource "aws_cloudtrail" "secrets_audit" {
  name                          = "${var.environment}-vesting-secrets-audit"
  include_global_service_events = false
  is_multi_region_trail         = false
  enable_log_file_validation    = true
  kms_key_id                    = aws_kms_key.secrets.arn
  cloudwatch_logs_group_arn     = "${aws_cloudwatch_log_group.secrets_audit.arn}:*"
  cloudwatch_logs_role_arn      = aws_iam_role.cloudtrail.arn

  event_selector {
    read_write_type           = "All"
    include_management_events = false

    data_resource {
      type   = "AWS::SecretsManager::Secret"
      values = ["vesting/${var.environment}/*"]
    }
  }
}
