variable "environment" {
  description = "Deployment environment (staging, production)"
  type        = string
}

variable "aws_region" {
  description = "AWS region hosting the secrets and the audit trail."
  type        = string
}

variable "db_identifier" {
  description = "RDS instance identifier whose master password this module rotates."
  type        = string
}

variable "db_address" {
  description = "RDS instance hostname, stored alongside the password so the rotation Lambda can verify the new credential."
  type        = string
}

variable "db_port" {
  description = "RDS instance port."
  type        = number
  default     = 5432
}

variable "db_name" {
  description = "Initial PostgreSQL database name."
  type        = string
  default     = "vesting"
}

variable "db_username" {
  description = "RDS master username."
  type        = string
  default     = "vesting"
}

variable "db_password" {
  description = "Bootstrap master password for the PostgreSQL RDS instance. Generated by Terraform rather than supplied by CI."
  type        = string
  sensitive   = true
}

variable "rotation_days" {
  description = "Days between automatic database password rotations."
  type        = number
  default     = 30
}

variable "slack_webhook_url" {
  description = "Bootstrap Slack incoming webhook for the alert relay. Replace with `aws secretsmanager put-secret-value` after first apply."
  type        = string
  sensitive   = true
}

variable "soroban_rpc_api_key" {
  description = "Optional Soroban RPC API key. When empty a random placeholder is stored."
  type        = string
  default     = ""
  sensitive   = true
}

variable "sentry_dsn" {
  description = "Optional Sentry DSN. When empty a random placeholder is stored."
  type        = string
  default     = ""
  sensitive   = true
}

variable "alert_emails" {
  description = "Email recipients notified when a secret rotation fails."
  type        = set(string)
  default     = []
}
